trigger:
  none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Docker@2
    displayName: 'Test DockerHub connection'
    inputs:
      containerRegistry: 'dockerhub-ebtwim'
      command: 'login'
