trigger:
  none  # لا يعمل تلقائيًا

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  displayName: 'Get AKS Credentials and Create Namespace'
  inputs:
    azureSubscription: 'Azure-subscription-for-Capstone'  # اسم Service Connection من نوع ARM
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Getting AKS credentials..."
      az aks get-credentials \
        --resource-group DevOps1-CapstoneProject-champ-rg \
        --name DevOps1-CapstoneProject-champ-aks \
        --overwrite-existing

      echo "Creating namespace (if not exists)..."
      kubectl get namespace project || kubectl create namespace project
