trigger:
  none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Kubernetes@1
  displayName: 'Create Namespace (project)'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'k8s-connection'
    command: 'apply'
    arguments: '-f -'
    secretType: 'None'
    useConfigurationFile: false
    inline: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: project
