trigger:
  none  # لا يعمل تلقائيًا

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Kubernetes@1
  displayName: 'Create Namespace (project)'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'k8s-connection'
    command: 'apply'
    useConfigurationFile: true
    configuration: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: project
