trigger:
  none  # تشغيل يدوي فقط

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: echo "🚀 Testing DockerHub connection..."
    displayName: 'Start Test'

  - task: Docker@2
    displayName: 'Login to DockerHub'
    inputs:
      containerRegistry: 'dockerhub-ebtwim'
      command: 'login'
